[package]
name = "topic_validator"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Wubben"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
